name: bigwig-loader
channels:
  - rapidsai
  - rapidsai-nightly
  - conda-forge
  - nvidia
  - bioconda
dependencies:
  - python>=3.9,<3.11
  - pip
  - cython>=0.29,<0.30
  - c-compiler

  - kvikio>=24.06.00a
  - cupy>=12.0.0
  - numpy>=1.21
  - pandas
  - pyfaidx
  - ncls
  - htslib
  - pydantic
  - pydantic-settings
  - python-dotenv
  - universal_pathlib
  - natsort

  - pip:
      - -e .[dev]
